### ISSUE TITLE
nginx cache and E-tag settings

### ISSUE THREAD

**Issue by pekrau** [ScilifelabDataCentre/covid-hub#21]
Ensure that newly edited content is refreshed by the browser.
- Set caching for HTML to no-cache, at least until development is less hectic.
- Ensure that E-tag is used.

See https://stackoverflow.com/questions/499966/etag-vs-header-expires
and https://www.digitalocean.com/community/tutorials/how-to-implement-browser-caching-with-nginx-s-header-module-on-ubuntu-16-04

**Comment by talavis** [comment]
Do we want this for both production and dev, or only dev?

Etags should be set by default.

Which parts do we want caching for? E.g. do we want to have no caching for html pages, but long caching of css, js, images etc?
```
map $sent_http_content_type $expires {
    default                    off;
    text/html                  epoch;
    text/css                   max;
    application/javascript     max;
    ~image/                    max;
}
```

**Comment by ewels** [comment]
I think both for now. Can always turn production off at a later date.

Can CSS etc be set to 1 day or something as a compromise?

**Comment by pekrau** [comment]
While we are changing the site often, caching should be very short-lived, if at all. So your scheme looks good for now.
And yes, same policy for both, I would say. For now.
